
@startmindmap puml
* root
 * https:§§cloud.google.com§api-gateway
  * §docs
  * §about-api-gateway
  * §architecture-overview
  * §authenticate-service-account
  * §authenticating-users-auth0
  * §authentication-method
  * §configure-dev-env
  * §creating-api
  * -config
  * §deploying-api
  * §how-to
  * §openapi-overview
  * §passing-data
  * §quickstart
  * §quotas-overview
 * https:§§cloud.google.com§apis§docs§cloud-client-libraries
 * https:§§cloud.google.com§architecture
  * §bigquery-data-warehouse
 * https:§§cloud.google.com§bigquery§docs
  * §bq-command-line-tool
  * §how-to
  * §introduction
  * §loading-data
  * §nested-repeated#python
  * §quickstarts
  * §quickstart-client-libraries
  * §quickstart-command-line
  * §quickstart-web-ui
  * §reference§bq-cli-reference
  * §reference§rest
  * §running-queries
 * https:§§cloud.google.com§bigquery§streaming-data-into-bigquery
 * https:§§cloud.google.com§blog§products§data-analytics§create-templates-from-any-dataflow-pipeline
 * https:§§cloud.google.com§blog§topics§developers-practitioners§bigquery-admin-reference-guide-data-governance
 * https:§§cloud.google.com§code§docs§vscode§client-libraries
 * https:§§cloud.google.com§code§docs§vscode§install
 * https:§§cloud.google.com§dataflow
  * §docs§concepts§dataflow-templates
  * §docs§guides§templates§configuring-flex-templates
  * §docs§guides§templates§creating-templates
  * §docs§guides§templates§provided-templates
  * §docs§guides§templates§running-templates
  * §docs§guides§templates§using-flex-templates
  * §docs§quickstarts
  * §quickstart-python
 * https:§§cloud.google.com§docs
  * §authentication
  * §overview
 * https:§§cloud.google.com§endpoints§docs§openapi§authenticating-users-auth0
 * https:§§cloud.google.com§functions
  * §docs
  * §bestpractices§tips
  * §calling
  * §pubsub#functions_calling_pubsub-python
  * §concepts§overview
  * §first-python
  * §how-to
  * §quickstart
  * -python
  * §writing
  * §quotas
 * https:§§cloud.google.com§iam§docs§creating-managing-service-accounts
 * https:§§cloud.google.com§logging
 * https:§§cloud.google.com§obar1
 * https:§§cloud.google.com§products
  * §operations
 * https:§§cloud.google.com§pubsub
  * §docs
  * §overview
  * §quickstart-client-libraries
  * §quickstart-console
 * https:§§cloud.google.com§scheduler§docs§tut-pub-sub
 * https:§§cloud.google.com§sdk
  * §gcloud§reference§functions
 * https:§§cloud.google.com§sql
  * §docs§mysql§create-instance
  * §docs§mysql§quickstart
 * https:§§cloud.google.com§storage
 * https:§§cloud.google.com§xxx
 * https:§§google.qwiklabs.com§quests§35
 * https:§§google.qwiklabs.com§quests§81

@endmindmap
        